# Generated by Django 5.0.5 on 2024-05-08 10:38

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('inherited', 'Inherited')], default='inherited', max_length=10)),
                ('children_position', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('content_classList', models.JSONField(blank=True, default=api.models.default_content_class_list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('classList', models.JSONField(blank=True, default=api.models.default_class_list)),
                ('layout', models.CharField(blank=True, choices=[('default', 'Default'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('table', 'Table')], default='default', max_length=50)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('children', models.ManyToManyField(blank=True, related_name='parent_blocks', to='api.block')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
                ('editable_by_users', models.ManyToManyField(blank=True, related_name='editable_blocks', to=settings.AUTH_USER_MODEL)),
                ('visible_to_users', models.ManyToManyField(blank=True, related_name='visible_blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
