# Generated by Django 5.0.5 on 2024-05-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blockchangelog_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='status',
            new_name='access_type',
        ),
    ]
