# Generated by Django 5.0.5 on 2024-05-08 12:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_status_block_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='children_position',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='classList',
            field=models.JSONField(blank=True, default=api.models.default_class_list, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='content_classList',
            field=models.JSONField(blank=True, default=api.models.default_content_class_list, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
